jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin123"
          name: "Administrator"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  systemMessage: "RetailTech DevOps CI/CD Environment 🚀"
  numExecutors: 2
  mode: NORMAL


credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "sonarqube-token"
              secret: "changeme"
              description: "SonarQube authentication token"

jobs:
  - script: >
      pipelineJob('product-service-cd') {
        description('🚀 CD Pipeline - RetailTech Product Service')
        keepDependencies(false)
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/EdissonSteven/project-dev-ops.git')
                  credentials('')
                }
                branches('*/main', '*/develop')
                extensions {
                  wipeOutWorkspace()
                }
              }
            }
            scriptPath('lab3-reatiltech-app/Jenkinsfile')
            lightweight(false)
          }
        }
        triggers {
          scm('H/2 * * * *')
        }
        logRotator {
          numToKeep(10)
        }
      }

tool:
  git:
    installations:
      - name: "Default"
        home: "git"

  nodejs:
    installations:
      - name: "Node 18"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "18.19.0"
                    npmPackagesRefreshHours: 72

unclassified:
  location:
    url: "http://localhost:8080/"
    adminAddress: "devops@retailtech.com"

  sonarGlobalConfiguration:
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonarqube-token"

  gitHubPluginConfig:
    configs:
      - name: "GitHub"
        apiUrl: "https://api.github.com"
